@extends('layouts.app')
@section('title', 'Transferência #'.$transfer->id)
@section('content')
    <div class="page-header"><div><div class="flex flex-wrap items-center gap-3"><h1 class="page-title">Transferência #{{ $transfer->id }}</h1><span class="status-badge {{ $transfer->status === \App\Enums\StockTransferStatus::Received ? 'status-active' : 'status-inactive' }}">{{ $transfer->status->label() }}</span></div><p class="page-subtitle">{{ $transfer->sourceLocation->name }} → {{ $transfer->destinationLocation->name }}</p></div><a class="btn-secondary" href="{{ route('transfers.index') }}">Voltar</a></div>
    @if ($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="mb-6 grid gap-4 sm:grid-cols-3"><div class="metric-card"><p class="metric-label">Planejada em</p><p class="metric-value">{{ $transfer->operation_date->format('d/m/Y') }}</p></div><div class="metric-card"><p class="metric-label">Expedida em</p><p class="metric-value">{{ $transfer->dispatched_date?->format('d/m/Y') ?? '—' }}</p></div><div class="metric-card"><p class="metric-label">Recebida em</p><p class="metric-value">{{ $transfer->received_date?->format('d/m/Y') ?? '—' }}</p></div></div>
    <div class="table-card mb-6"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Produto</th><th>Enviado</th><th>Recebido</th><th>Diferença</th></tr></thead><tbody>@foreach ($transfer->items as $item)<tr><td class="font-semibold">{{ $item->product->name }}</td><td>{{ \App\Support\DecimalFormatter::format($item->quantity_sent, $item->product->stock_unit === 'un' ? 0 : 3) }} {{ $item->product->stock_unit }}</td><td>{{ $item->quantity_received !== null ? \App\Support\DecimalFormatter::format($item->quantity_received, $item->product->stock_unit === 'un' ? 0 : 3).' '.$item->product->stock_unit : 'Aguardando' }}</td><td>@if ($item->quantity_received !== null){{ \App\Support\DecimalFormatter::format((string) \Brick\Math\BigDecimal::of($item->quantity_received)->minus($item->quantity_sent), $item->product->stock_unit === 'un' ? 0 : 3) }} {{ $item->product->stock_unit }}@else — @endif</td></tr>@endforeach</tbody></table></div></div>
    @if ($transfer->status === \App\Enums\StockTransferStatus::Pending)
        <div class="grid gap-6 lg:grid-cols-2">@if($canDispatch)<form method="POST" action="{{ route('transfers.dispatch', $transfer) }}" class="form-card">@csrf<h2 class="mb-4 text-lg font-bold">Expedir transferência</h2><label class="form-label" for="dispatched_date">Data real da expedição</label><input id="dispatched_date" name="dispatched_date" type="date" class="form-input" required value="{{ old('dispatched_date', now()->toDateString()) }}"><p class="mt-3 text-sm text-stone-500">A expedição retira os itens do estoque da origem.</p><button class="btn-primary mt-5" type="submit">Expedir e baixar origem</button></form>@endif @if($canCancel)<form method="POST" action="{{ route('transfers.cancel', $transfer) }}" class="form-card">@csrf<h2 class="mb-4 text-lg font-bold">Cancelar transferência</h2><p class="text-sm text-stone-600">Como ainda não foi expedida, o cancelamento não movimenta estoque.</p><button class="btn-secondary mt-5" type="submit">Cancelar</button></form>@endif</div>
    @elseif ($transfer->status === \App\Enums\StockTransferStatus::InTransit)
        @if($canReceive)<form method="POST" action="{{ route('transfers.receive', $transfer) }}" class="form-card">@csrf<h2 class="mb-4 text-lg font-bold">Confirmar recebimento</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="form-label" for="received_date">Data real do recebimento</label><input id="received_date" name="received_date" type="date" class="form-input" required value="{{ old('received_date', now()->toDateString()) }}"></div>@foreach ($transfer->items as $item)<div><label class="form-label" for="received_{{ $item->id }}">{{ $item->product->name }} recebido ({{ $item->product->stock_unit }})</label><input id="received_{{ $item->id }}" name="received_quantities[{{ $item->id }}]" type="number" min="0" step="0.000001" class="form-input" required value="{{ old('received_quantities.'.$item->id, $item->quantity_sent) }}"></div>@endforeach</div><p class="mt-3 text-sm text-stone-500">O destino recebe a quantidade real informada; diferenças ficam registradas.</p><button class="btn-primary mt-5" type="submit">Confirmar recebimento</button></form>@endif
    @elseif ($transfer->status === \App\Enums\StockTransferStatus::Received)
        <div class="grid gap-6 lg:grid-cols-2">
            <div class="form-card"><p class="text-sm text-stone-600">{{ $transfer->notes ?: 'Sem observações.' }}</p></div>
            @if($canReverse)<form method="POST" action="{{ route('transfers.reverse', $transfer) }}" class="form-card">@csrf<h2 class="mb-4 text-lg font-bold">Estornar transferência</h2><label class="form-label" for="reversal_date">Data real do estorno</label><input id="reversal_date" name="reversal_date" type="date" class="form-input" required value="{{ old('reversal_date', now()->toDateString()) }}"><label class="form-label mt-4" for="reason">Motivo</label><textarea id="reason" name="reason" rows="3" class="form-input" required>{{ old('reason') }}</textarea><p class="mt-3 text-sm text-stone-500">O histórico será preservado e os saldos serão corrigidos por movimentos compensatórios.</p><button class="btn-secondary mt-5" type="submit">Estornar com auditoria</button></form>@endif
        </div>
    @else
        <div class="form-card"><p class="text-sm text-stone-600">{{ $transfer->notes ?: 'Sem observações.' }}</p></div>
        @if($transfer->status === \App\Enums\StockTransferStatus::Reversed)<div class="form-card mt-4"><p class="text-sm font-semibold">Estornada em {{ $transfer->reversal_date?->format('d/m/Y') }} por {{ $transfer->reversal_reason }}.</p></div>@endif
    @endif
@endsection
