@extends('layouts.app')
@section('title', 'Custos e margens')
@section('content')
<div class="page-header"><div><h1 class="page-title">Custos e margens</h1><p class="page-subtitle">Custo de reposição atual e memória histórica, sem alterar automaticamente o preço de venda.</p></div></div>
<form class="form-card mb-6 flex flex-wrap items-end gap-3" method="GET"><label><span class="form-label">Posição histórica</span><input class="form-input" type="date" name="date" value="{{ $date }}"></label><button class="btn-primary">Aplicar</button><a class="btn-secondary" href="{{ route('costs.index') }}">Hoje</a></form>
<div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Produto</th><th>Preço de venda</th><th>Custo</th><th>Lucro bruto estimado</th><th>Margem estimada</th><th>Markup</th><th>7d custo / margem</th><th>30d custo / margem</th><th>90d custo / margem</th><th>Ficha</th></tr></thead><tbody>
@foreach($rows as $row)<tr><td class="font-semibold">{{ $row['product']->name }}</td><td>{{ $row['sellingPrice'] === null ? 'Sem preço' : 'R$ '.\App\Support\DecimalFormatter::format($row['sellingPrice'],2) }}</td>
<td>@if($row['unit_cost'] !== null)R$ {{ \App\Support\DecimalFormatter::format($row['unit_cost'],4) }}@elseif($row['partial_unit_cost'] !== null)<span class="font-semibold text-amber-700">Subtotal conhecido: R$ {{ \App\Support\DecimalFormatter::format($row['partial_unit_cost'],4) }}</span>@else<span class="text-stone-500">Sem custo calculado</span>@endif</td><td>{{ $row['gross_profit'] === null ? '—' : 'R$ '.\App\Support\DecimalFormatter::format($row['gross_profit'],2) }}</td><td>{{ $row['gross_margin_percentage'] === null ? '—' : \App\Support\DecimalFormatter::format($row['gross_margin_percentage'],2).'%' }}</td><td>{{ $row['markup_percentage'] === null ? '—' : \App\Support\DecimalFormatter::format($row['markup_percentage'],2).'%' }}</td>
@foreach([7,30,90] as $days)<td><span class="block">{{ $row['variations'][$days] === null ? '—' : \App\Support\DecimalFormatter::format($row['variations'][$days],2).'%' }}</span><span class="block text-xs text-stone-500">Margem: {{ $row['margin_variations'][$days] === null ? '—' : \App\Support\DecimalFormatter::format($row['margin_variations'][$days],2).' p.p.' }}</span></td>@endforeach
<td>@if($row['status']==='recipe_pending')<span class="status-badge status-inactive">Ficha técnica pendente</span>@elseif($row['status']==='incomplete_cost')<span class="status-badge">Custo parcial</span>@if($row['missing_components'] !== [])<ul class="mt-2 list-disc pl-4 text-xs text-stone-600">@foreach($row['missing_components'] as $component)<li>{{ $component }}</li>@endforeach</ul>@endif @else<span class="status-badge status-active">Completa</span>@endif</td></tr>@endforeach
</tbody></table></div></div>

<div class="page-header mt-10"><div><h2 class="text-2xl font-bold">Variação dos insumos</h2><p class="page-subtitle">Somente compras e preços confirmados; cotações não entram nas médias.</p></div></div>
<form class="form-card mb-6 flex flex-wrap items-end gap-3" method="GET">
    @if($date)<input type="hidden" name="date" value="{{ $date }}">@endif
    <label><span class="form-label">Período</span><select class="form-input" name="period"><option value="7" @selected($period==='7')>7 dias</option><option value="30" @selected($period==='30')>30 dias</option><option value="90" @selected($period==='90')>90 dias</option><option value="custom" @selected($period==='custom')>Personalizado</option></select></label>
    <label><span class="form-label">Início</span><input class="form-input" type="date" name="start_date" value="{{ $period === 'custom' ? $startDate->toDateString() : '' }}"></label>
    <label><span class="form-label">Fim</span><input class="form-input" type="date" name="end_date" value="{{ $period === 'custom' ? $endDate->toDateString() : '' }}"></label>
    <button class="btn-primary">Aplicar</button>
</form>
<div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Insumo</th><th>Preço inicial</th><th>Preço final</th><th>Variação R$</th><th>Variação %</th><th>Último fornecedor</th><th>Impacto</th></tr></thead><tbody>
@forelse($ingredientVariations as $row)<tr><td class="font-semibold">{{ $row['ingredient']->name }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($row['initial']->base_unit_cost,4) }} / {{ $row['ingredient']->base_unit }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($row['final']->base_unit_cost,4) }} / {{ $row['ingredient']->base_unit }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($row['difference'],4) }}</td><td>{{ $row['variation_percentage'] === null ? '—' : \App\Support\DecimalFormatter::format($row['variation_percentage'],2).'%' }}</td><td>{{ $row['latest_supplier']->name }}<span class="block text-xs text-stone-500">{{ $row['purchases_count'] }} registro(s)</span></td><td>@forelse($row['impacted_products'] as $product)<span class="status-badge mr-1 mb-1">{{ $product }}</span>@empty<span class="text-sm text-stone-500">Sem ficha vinculada</span>@endforelse</td></tr>@empty<tr><td colspan="7" class="empty-state">Nenhum preço confirmado no período.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
