@extends('layouts.app')
@section('title', 'Conciliação GrandChef × ERP')
@section('content')
    <div class="space-y-6">
        <div><p class="text-sm font-semibold uppercase tracking-wider text-amber-700">{{ $connection->location->name }}</p><h1 class="text-3xl font-bold">Conciliação GrandChef × ERP</h1><p class="mt-2 text-sm text-stone-600">Comparação somente leitura. Esta tela não cria venda, financeiro nem movimento de estoque.</p></div>
        <form class="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-[1fr_1fr_auto]"><label class="text-sm font-semibold">De<input class="mt-1 w-full rounded-lg border-stone-300" type="date" name="from" value="{{ $from }}"></label><label class="text-sm font-semibold">Até<input class="mt-1 w-full rounded-lg border-stone-300" type="date" name="to" value="{{ $to }}"></label><button class="self-end rounded-lg bg-stone-900 px-5 py-2.5 font-bold text-white">Comparar</button></form>
        <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            @foreach ([['Pedidos externos', $result['summary']['external_orders']], ['Importados', $result['summary']['imported']], ['Pré-operação', $result['summary']['pre_operational']], ['Bloqueados', $result['summary']['blocked']], ['Prontos', $result['summary']['ready']], ['Cancelados', $result['summary']['cancelled']], ['Revertidos', $result['summary']['reversed']], ['Inconsistências', $result['summary']['inconsistencies']]] as [$label, $value])
                <div class="rounded-xl border bg-white p-4"><p class="text-xs font-bold uppercase text-stone-500">{{ $label }}</p><p class="mt-1 text-2xl font-bold">{{ $value }}</p></div>
            @endforeach
        </section>
        <section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            @foreach ([['Total externo bruto', $result['summary']['external_total']], ['Externo comparável', $result['summary']['comparable_external_total']], ['Total oficial ERP', $result['summary']['official_total']], ['Diferença', $result['summary']['difference']]] as [$label, $value])
                <div class="rounded-xl border bg-white p-4"><p class="text-xs font-bold uppercase text-stone-500">{{ $label }}</p><p class="mt-1 text-xl font-bold">R$ {{ \App\Support\DecimalFormatter::format($value) }}</p></div>
            @endforeach
        </section>
        <section class="grid gap-4 lg:grid-cols-2"><div class="rounded-xl border bg-white p-5"><h2 class="font-bold">Pagamentos externos</h2><div class="mt-3 space-y-2">@forelse($result['external_payments'] as $payment)<p class="flex justify-between text-sm"><span>{{ $payment['label'] }} · {{ $payment['count'] }}</span><strong>R$ {{ \App\Support\DecimalFormatter::format($payment['total']) }}</strong></p>@empty<p class="text-sm text-stone-500">Nenhum pagamento externo.</p>@endforelse</div></div><div class="rounded-xl border bg-white p-5"><h2 class="font-bold">Pagamentos oficiais ERP</h2><div class="mt-3 space-y-2">@forelse($result['official_payments'] as $payment)<p class="flex justify-between text-sm"><span>{{ $payment['label'] }} · {{ $payment['count'] }}</span><strong>R$ {{ \App\Support\DecimalFormatter::format($payment['total']) }}</strong></p>@empty<p class="text-sm text-stone-500">Nenhum pagamento oficial.</p>@endforelse</div></div></section>
        <section class="rounded-xl border bg-white"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-stone-50 text-xs uppercase text-stone-500"><tr><th class="px-4 py-3">Pedido</th><th class="px-4 py-3">Conclusão</th><th class="px-4 py-3">Classificação</th><th class="px-4 py-3">Externo</th><th class="px-4 py-3">ERP</th><th class="px-4 py-3">Bloqueios</th></tr></thead><tbody class="divide-y">@forelse($result['rows'] as $row)<tr><td class="px-4 py-3"><a class="font-bold text-amber-700" href="{{ route('pdv.staging.show', [$connection, $row['order']]) }}">{{ $row['order']->external_code ?? $row['order']->external_order_id }}</a></td><td class="whitespace-nowrap px-4 py-3">{{ $row['order']->external_completed_at?->setTimezone(config('app.timezone'))->format('d/m/Y H:i') ?? '—' }}</td><td class="px-4 py-3 font-semibold">{{ str_replace('_', ' ', $row['classification']) }}</td><td class="px-4 py-3">R$ {{ \App\Support\DecimalFormatter::format($row['external_total']) }}</td><td class="px-4 py-3">R$ {{ \App\Support\DecimalFormatter::format($row['official_total']) }}</td><td class="px-4 py-3">{{ collect($row['blockers'])->pluck('code')->join(', ') ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="px-4 py-8 text-center text-stone-500">Nenhum pedido no período.</td></tr>@endforelse</tbody></table></div></section>
    </div>
@endsection
