@extends('layouts.app')
@section('title', 'Novo documento')
@section('content')
<div class="page-header"><div><h1 class="page-title">Novo documento de fornecedor</h1><p class="page-subtitle">Lançamento manual com vários itens. Para OCR, use a revisão por foto.</p></div><div class="flex gap-2"><a class="btn-secondary" href="{{ route('purchase-imports.create') }}">Enviar foto</a><a class="btn-secondary" href="{{ route('purchases.index') }}">Voltar</a></div></div>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
<form class="space-y-6" method="POST" action="{{ route('purchases.store') }}">@csrf<input type="hidden" name="idempotency_key" value="{{ $key }}"><input type="hidden" name="currency" value="BRL">
<section class="form-card"><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
<label><span class="form-label">Tipo</span><select class="form-input" name="document_type"><option value="invoice">Nota fiscal</option><option value="receipt">Cupom/recibo</option><option value="order">Pedido de compra</option><option value="quote">Cotação</option><option value="boleto">Boleto</option><option value="bill">Fatura</option><option value="other">Outro</option></select></label>
<label><span class="form-label">Número</span><input class="form-input" name="document_number" value="{{ old('document_number') }}"></label><label><span class="form-label">Série</span><input class="form-input" name="series" value="{{ old('series') }}"></label>
<label><span class="form-label">Fornecedor</span><select class="form-input" name="supplier_id"><option value="">Não identificado</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id')==$supplier->id)>{{ $supplier->name }}</option>@endforeach</select></label>
<label><span class="form-label">Unidade</span><select class="form-input" name="location_id">@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select></label>
<label><span class="form-label">Emissão</span><input class="form-input" type="date" name="issue_date" value="{{ old('issue_date',now()->toDateString()) }}" required></label><label><span class="form-label">Vencimento</span><input class="form-input" type="date" name="due_date" value="{{ old('due_date') }}"></label>
<label><span class="form-label">Subtotal</span><input class="form-input" name="gross_amount" value="{{ old('gross_amount') }}"></label><label><span class="form-label">Desconto</span><input class="form-input" name="discount_amount" value="{{ old('discount_amount','0.00') }}"></label><label><span class="form-label">Frete</span><input class="form-input" name="freight_amount" value="{{ old('freight_amount','0.00') }}"></label><label><span class="form-label">Acréscimos</span><input class="form-input" name="other_charges_amount" value="{{ old('other_charges_amount','0.00') }}"></label><label><span class="form-label">Valor total</span><input class="form-input font-bold" name="total_amount" value="{{ old('total_amount') }}" required></label>
</div></section>
<section><div class="mb-3"><h2 class="text-xl font-bold">Itens</h2><p class="text-sm text-stone-500">Preencha somente as linhas necessárias. Itens vinculados a insumos formarão o histórico de custos; uma cotação ficará separada das compras efetivas.</p></div><div class="space-y-3">
@for($index=0;$index<8;$index++)<div class="form-card grid gap-3 sm:grid-cols-2 lg:grid-cols-10"><label class="lg:col-span-2"><span class="form-label">Descrição</span><input class="form-input" name="items[{{ $index }}][description]" value="{{ old("items.$index.description") }}"></label><label class="lg:col-span-2"><span class="form-label">Insumo</span><select class="form-input" name="items[{{ $index }}][ingredient_id]"><option value="">Não vinculado</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}" @selected(old("items.$index.ingredient_id")==$ingredient->id)>{{ $ingredient->name }}</option>@endforeach</select></label><label><span class="form-label">Quantidade</span><input class="form-input" name="items[{{ $index }}][quantity]" value="{{ old("items.$index.quantity") }}"></label><label><span class="form-label">Unidade</span><select class="form-input" name="items[{{ $index }}][unit]">@foreach(['kg','g','l','ml','un'] as $unit)<option @selected(old("items.$index.unit")===$unit)>{{ $unit }}</option>@endforeach</select></label><label><span class="form-label">Nº embalagens</span><input class="form-input" name="items[{{ $index }}][package_quantity]" value="{{ old("items.$index.package_quantity") }}"></label><label><span class="form-label">Tamanho</span><input class="form-input" name="items[{{ $index }}][package_size]" value="{{ old("items.$index.package_size") }}"></label><label><span class="form-label">Un. embalagem</span><select class="form-input" name="items[{{ $index }}][package_unit]"><option value="">—</option>@foreach(['kg','g','l','ml','un'] as $unit)<option @selected(old("items.$index.package_unit")===$unit)>{{ $unit }}</option>@endforeach</select></label><label><span class="form-label">Total do item</span><input class="form-input" name="items[{{ $index }}][total_price]" value="{{ old("items.$index.total_price") }}"><input type="hidden" name="items[{{ $index }}][unit_price]" value="0"></label></div>@endfor
</div></section>
<button class="btn-primary">Salvar documento</button></form>
@endsection
