@extends('layouts.app')
@section('title', 'Documento de compra')
@section('content')
<div class="page-header"><div><h1 class="page-title">Documento #{{ $document->id }}</h1><p class="page-subtitle">{{ $document->supplier?->name ?? 'Fornecedor pendente' }} · {{ $document->location->name }} · {{ $document->issue_date->format('d/m/Y') }}</p></div><a class="btn-secondary" href="{{ route('purchases.index') }}">Voltar</a></div>
@if($errors->any())<div class="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div class="metric-card"><p class="metric-label">Total</p><p class="metric-value">R$ {{ \App\Support\DecimalFormatter::format($document->total_amount,2) }}</p></div><div class="metric-card"><p class="metric-label">Recebimento</p><p class="metric-value text-xl">{{ str_replace('_',' ',$document->receipt_status) }}</p></div><div class="metric-card"><p class="metric-label">Origem econômica</p><p class="metric-value text-xl">{{ str_replace('_',' ',$document->source_type) }}</p></div><div class="metric-card"><p class="metric-label">Vencimento</p><p class="metric-value text-xl">{{ $document->due_date?->format('d/m/Y') ?? 'Pendente' }}</p></div><div class="metric-card"><p class="metric-label">Série / número</p><p class="metric-value text-xl">{{ $document->series ?: '—' }} / {{ $document->document_number ?: '—' }}</p></div></div>

<section class="mt-6"><h2 class="mb-3 text-xl font-bold">Itens e memória de custo</h2><div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Item</th><th>Insumo</th><th>Compra</th><th>Total</th><th>Custo normalizado</th><th>Recebido</th></tr></thead><tbody>@forelse($document->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->ingredient?->name ?? 'Não vinculado' }}</td><td>{{ \App\Support\DecimalFormatter::format($item->quantity,3) }} {{ $item->unit }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($item->net_amount ?? $item->total_price,2) }}</td><td>{{ $item->normalized_unit_cost ? 'R$ '.\App\Support\DecimalFormatter::format($item->normalized_unit_cost,4).' / '.$item->normalized_unit : 'Pendente' }}</td><td>{{ \App\Support\DecimalFormatter::format($item->received_quantity,3) }} {{ $item->unit }}</td></tr>@empty<tr><td colspan="6" class="empty-state">Documento sem itens.</td></tr>@endforelse</tbody></table></div></div></section>

@if($document->source_type !== 'quote' && $document->items->isNotEmpty() && $document->receipt_status !== 'received')<form class="form-card mt-6" method="POST" action="{{ route('purchases.receipts.store',$document) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ $key }}"><h2 class="text-lg font-bold">Registrar recebimento físico</h2><p class="mt-1 text-sm text-stone-500">O estoque só muda com esta confirmação explícita.</p><input class="form-input mt-3 max-w-xs" type="date" name="received_date" value="{{ now()->toDateString() }}" required><div class="mt-4 table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Item</th><th>Total</th><th>Recebido</th><th>Pendente</th><th>Receber agora</th></tr></thead><tbody>@foreach($document->items as $item)@php($pending=\Brick\Math\BigDecimal::of($item->quantity)->minus($item->received_quantity??0))<tr><td>{{ $item->description }}</td><td>{{ $item->quantity }} {{ $item->unit }}</td><td>{{ $item->received_quantity ?? 0 }}</td><td>{{ $pending }}</td><td><input class="form-input w-36" name="quantities[{{ $item->id }}]" value="0" min="0" max="{{ $pending }}" step="0.000001"></td></tr>@endforeach</tbody></table></div></div><button class="btn-primary mt-4">Confirmar entrada física</button></form>@endif

@if($document->source_type !== 'quote')<form class="form-card mt-6" method="POST" action="{{ route('purchases.payable.store',$document) }}">@csrf<h2 class="text-lg font-bold">Obrigação financeira separada</h2><p class="mt-2 text-sm text-stone-600">A conta será criada somente por esta ação e se fornecedor, vencimento, categoria e centro de custo estiverem definidos.</p><button class="btn-secondary mt-4">Criar/vincular conta a pagar</button></form>@endif
@endsection
