@extends('layouts.app')
@section('title','Observabilidade do Agente')
@section('content')
<div class="page-header"><div><h1 class="page-title">Observabilidade do Agente</h1><p class="page-subtitle">Mensagens, Tools, confirmações, duplicidades e erros sanitizados.</p></div><a class="btn-secondary" href="{{ route('agent.identities.index') }}">Identidades</a></div>
<div class="mb-6 grid gap-3 sm:grid-cols-3 lg:grid-cols-5">@foreach(['today'=>'Mensagens hoje','month'=>'Mensagens mês','deterministic'=>'Sem IA','ai'=>'Com IA','tools'=>'Tools','denied'=>'Negadas','confirmations'=>'Confirmações','duplicates'=>'Duplicidades','errors'=>'Erros','whatsapp_messages'=>'WhatsApp autorizado','whatsapp_blocked'=>'Contatos bloqueados','whatsapp_sent'=>'WhatsApp enviado','whatsapp_failures'=>'Falhas de envio','whatsapp_statuses'=>'Status WhatsApp'] as $key=>$label)<div class="form-card"><p class="text-xs text-stone-500">{{ $label }}</p><p class="text-2xl font-bold">{{ $metrics[$key] }}</p></div>@endforeach</div>
<section class="form-card mb-6"><h2 class="section-title">Provider de interpretação</h2><div class="mt-3 grid gap-3 sm:grid-cols-3"><div><span class="form-label">Provider</span><strong>{{ $providerConfig['provider'] }}</strong></div><div><span class="form-label">Modelo de texto</span><strong>{{ $providerConfig['model'] ?: 'Não definido' }}</strong></div><div><span class="form-label">Status</span><strong>{{ $providerConfig['status'] }}</strong></div></div><p class="mt-3 text-xs text-stone-500">Credenciais nunca são exibidas nesta tela.</p></section>
<section class="form-card mb-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="section-title">Custo do Agente — mês atual</h2><p class="page-subtitle">Meta e IA são estimativas até a consolidação das faturas.</p></div><span class="status-badge {{ $costSummary['level']==='normal'?'status-active':'status-inactive' }}">{{ strtoupper($costSummary['level']) }}</span></div><div class="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">@foreach(['host'=>'Host/infra','meta'=>'WhatsApp Meta','text'=>'IA texto','vision'=>'Visão/documentos','audio'=>'Áudio','total'=>'TOTAL'] as $key=>$label)<div><span class="form-label">{{ $label }}</span><strong>R$ {{ number_format((float)$costSummary[$key],2,',','.') }}</strong></div>@endforeach</div><p class="mt-4 text-sm">Orçamento: R$ {{ number_format((float)$costSummary['budget'],2,',','.') }} · Modo economia: <strong>{{ $costSummary['saving_mode']?'ATIVO':'inativo' }}</strong></p></section>
<div class="mb-6 grid gap-6 lg:grid-cols-2"><section class="form-card"><h2 class="section-title">Política de custos</h2><form class="mt-4 grid gap-3 sm:grid-cols-2" method="POST" action="{{ route('agent.costs.update') }}">@csrf @method('PUT') @foreach(['monthly_budget'=>'Orçamento mensal','monthly_host_cost'=>'Host mensal','warning_threshold'=>'Atenção','saving_threshold'=>'Economia','critical_threshold'=>'Crítico'] as $field=>$label)<label><span class="form-label">{{ $label }} (R$)</span><input class="form-input" name="{{ $field }}" value="{{ $costSettings->$field }}"></label>@endforeach<label class="flex items-center gap-2"><input type="checkbox" name="automatic_saving_mode" value="1" @checked($costSettings->automatic_saving_mode)> Economia automática não essencial</label><div><button class="btn-primary">Salvar política</button></div></form></section><section class="form-card"><h2 class="section-title">Consumo por usuário</h2><div class="mt-4 space-y-3">@forelse($costByUser as $userName=>$items)<div><strong>{{ $userName }}</strong><div class="text-sm text-stone-600">@foreach($items as $item) {{ $item->usage_type }}: R$ {{ number_format((float)$item->total,2,',','.') }}@if(!$loop->last) · @endif @endforeach</div></div>@empty<p class="text-sm text-stone-500">Nenhum consumo estimado no mês.</p>@endforelse</div></section></div>
<section class="mb-6"><h2 class="section-title mb-3">Eventos recentes</h2><div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Data</th><th>Usuário</th><th>Canal</th><th>Evento</th><th>Tool</th><th>Status/erro</th><th></th></tr></thead><tbody>@foreach($events as $event)<tr><td>{{ $event->created_at->format('d/m/Y H:i:s') }}</td><td>{{ $event->user?->name ?? 'Não identificado' }}</td><td>{{ $event->channel }}</td><td>{{ $event->event_type }}</td><td>{{ $event->tool_name ?? '—' }}</td><td>{{ $event->error_code ?? $event->status ?? '—' }}</td><td>@if($event->conversation)<a class="text-link" href="{{ route('agent.interactions.show',$event->conversation) }}">Detalhes</a>@endif</td></tr>@endforeach</tbody></table></div></div><div class="mt-4">{{ $events->links() }}</div></section>
<section><h2 class="section-title mb-3">Ações pendentes e confirmações</h2><div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Criada</th><th>Usuário</th><th>Tool</th><th>Status</th><th>Expira</th><th>Payload seguro</th></tr></thead><tbody>@forelse($pendingActions as $action)<tr><td>{{ $action->created_at->format('d/m/Y H:i') }}</td><td>{{ $action->conversation?->user?->name ?? '—' }}</td><td>{{ $action->tool_name }}</td><td>{{ $action->status }}</td><td>{{ $action->expires_at?->format('d/m/Y H:i') ?? '—' }}</td><td><code>{{ \Illuminate\Support\Str::limit(json_encode($action->payload, JSON_UNESCAPED_UNICODE),100) }}</code></td></tr>@empty<tr><td colspan="6" class="empty-state">Nenhuma ação.</td></tr>@endforelse</tbody></table></div></div></section>
<section class="mb-6"><h2 class="section-title mb-3">Processamento WhatsApp</h2><div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Recebida</th><th>Mensagem</th><th>Status</th><th>Tentativas</th><th>Última falha</th><th>Próxima tentativa</th><th>Erro</th></tr></thead><tbody>@forelse($whatsappMessages as $message)<tr><td>{{ $message->received_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ \Illuminate\Support\Str::limit($message->external_message_id, 32) }}</td><td>{{ $message->status }}</td><td>{{ $message->attempts }}</td><td>{{ $message->last_failed_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $message->next_retry_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $message->error_code ?? '—' }}</td></tr>@empty<tr><td colspan="7" class="empty-state">Nenhuma mensagem processada.</td></tr>@endforelse</tbody></table></div></div></section>
@endsection
