@extends('layouts.app')
@section('title','Autorizar WhatsApp')
@section('content')
<div class="page-header"><div><h1 class="page-title">Autorizar telefone</h1><p class="page-subtitle">O telefone identifica a pessoa; funções e unidades continuam vindo do usuário ERP.</p></div><a class="btn-secondary" href="{{ route('agent.identities.index') }}">Voltar</a></div>
@if($errors->any())<div class="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('agent.identities.store') }}" class="space-y-6">@csrf
<section class="form-card"><h2 class="section-title">Identidade</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label><span class="form-label">Usuário ERP</span><select class="form-input" name="user_id" required><option value="">Selecione</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('user_id')==$user->id)>{{ $user->name }} · {{ $user->roles->pluck('label')->join(', ') ?: 'Sem perfil' }} · {{ $user->all_locations_access ? 'Todas as unidades' : ($user->locations->pluck('name')->join(', ') ?: 'Sem unidade') }}</option>@endforeach</select></label><label><span class="form-label">Telefone com DDD</span><input class="form-input" name="phone" value="{{ old('phone') }}" placeholder="(17) 99999-9999" required><span class="mt-1 block text-xs text-stone-500">Entradas brasileiras sem DDI serão normalizadas para +55.</span></label></div></section>
<section class="form-card"><h2 class="section-title">Política do canal</h2><p class="mt-1 text-sm text-stone-600">Essas opções não concedem permissões empresariais. O usuário também precisa possuir a permissão correspondente no ERP.</p><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['voice_allowed'=>'Áudio','image_allowed'=>'Imagem','document_allowed'=>'Documentos','reports_allowed'=>'Relatórios'] as $field=>$label)<label class="flex gap-2"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field))> {{ $label }}</label>@endforeach</div></section>
<label class="form-card flex items-start gap-3"><input class="mt-1" type="checkbox" name="confirm_authorization" value="1" required><span><strong>Confirmo o vínculo.</strong><span class="block text-sm text-stone-600">Revise o usuário e o telefone antes de ativar. Um número incorreto pode identificar a pessoa errada.</span></span></label>
<button class="btn-primary">Ativar acesso WhatsApp</button></form>
@endsection
