@extends('layouts.app')
@section('title','Gerenciar acesso WhatsApp')
@section('content')
<div class="page-header"><div><h1 class="page-title">{{ $identity->user?->name ?? 'Usuário removido' }}</h1><p class="page-subtitle">{{ $identity->phone_normalized }} · {{ $identity->active ? 'Acesso ativo' : 'Acesso inativo' }}</p></div><a class="btn-secondary" href="{{ route('agent.identities.index') }}">Voltar</a></div>
@if(session('success'))<div class="mb-5 rounded-xl bg-green-50 p-4 text-green-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
<div class="mb-6 grid gap-4 md:grid-cols-2"><section class="form-card"><h2 class="section-title">Identidade oficial</h2><dl class="mt-4 space-y-2 text-sm"><div><dt class="text-stone-500">Usuário</dt><dd class="font-semibold">{{ $identity->user?->name ?? '—' }}</dd></div><div><dt class="text-stone-500">Telefone normalizado</dt><dd>{{ $identity->phone_normalized }}</dd></div><div><dt class="text-stone-500">Perfil</dt><dd>{{ $identity->user?->roles?->pluck('label')->join(', ') ?: '—' }}</dd></div><div><dt class="text-stone-500">Unidades</dt><dd>{{ $identity->user?->all_locations_access ? 'Todas' : ($identity->user?->locations?->pluck('name')->join(', ') ?: '—') }}</dd></div><div><dt class="text-stone-500">Ativado por</dt><dd>{{ $identity->approver?->name ?? '—' }} · {{ $identity->activated_at?->format('d/m/Y H:i') ?? '—' }}</dd></div></dl></section><section class="form-card"><h2 class="section-title">Permissões efetivas em tempo real</h2><div class="mt-4 flex max-h-52 flex-wrap gap-2 overflow-y-auto">@forelse($effective as $name)<span class="status-badge status-active">{{ $name }}</span>@empty<span class="text-sm text-stone-500">Sem permissões efetivas.</span>@endforelse</div><p class="mt-3 text-xs text-stone-500">Altere cargos, permissões individuais e unidades na administração do usuário, não no telefone.</p></section></div>
<form method="POST" action="{{ route('agent.identities.update',$identity) }}" class="space-y-6">@csrf @method('PUT')
<section class="form-card"><h2 class="section-title">Acesso conversacional</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label><span class="form-label">Status</span><select class="form-input" name="status">@foreach(['approved'=>'Aprovado','blocked'=>'Bloqueado','inactive'=>'Inativo'] as $key=>$label)<option value="{{ $key }}" @selected($identity->status===$key)>{{ $label }}</option>@endforeach</select></label><label class="flex items-center gap-2 pt-6"><input type="checkbox" name="active" value="1" @checked($identity->active)> Acesso ativo</label></div><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['menu_enabled'=>'Menu','structured_commands_allowed'=>'Comandos','free_chat_allowed'=>'Conversa livre','voice_allowed'=>'Áudio','image_allowed'=>'Imagem','document_allowed'=>'Documentos','reports_allowed'=>'Relatórios'] as $field=>$label)<label class="flex gap-2"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field,$identity->$field))> {{ $label }}</label>@endforeach</div><button class="btn-primary mt-5">Salvar política</button></section></form>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><form method="POST" action="{{ route('agent.identities.phone',$identity) }}" class="form-card">@csrf @method('PUT')<h2 class="section-title">Trocar telefone</h2><p class="mt-1 text-sm text-stone-600">O número atual será desativado e ações pendentes serão canceladas.</p><label class="mt-4 block"><span class="form-label">Novo telefone</span><input class="form-input" name="phone" placeholder="(17) 99999-9999" required></label><label class="mt-3 flex gap-2"><input type="checkbox" name="confirm_replace" value="1" required> Confirmo a substituição</label><button class="btn-secondary mt-4">Trocar com segurança</button></form><form method="POST" action="{{ route('agent.identities.welcome',$identity) }}" class="form-card">@csrf<h2 class="section-title">Boas-vindas</h2><p class="mt-1 text-sm text-stone-600">Status: {{ $identity->welcome_status }}. Com Meta desligada, nenhuma mensagem real será enviada.</p><button class="btn-secondary mt-4" @disabled(!$identity->active)>Solicitar boas-vindas</button></form></div>
@endsection
