@extends('layouts.app')
@section('title','Gerenciar identidade')
@section('content')
<div class="page-header"><div><h1 class="page-title">{{ $identity->display_name ?? $identity->external_user_id }}</h1><p class="page-subtitle">{{ $identity->channel }} · {{ $identity->external_user_id }}</p></div><a class="btn-secondary" href="{{ route('agent.identities.index') }}">Voltar</a></div>
@if($errors->any())<div class="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('agent.identities.update',$identity) }}" class="space-y-6">@csrf @method('PUT')
<section class="form-card"><h2 class="section-title">Identidade e aprovação</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label><span class="form-label">Nome informado</span><input class="form-input" name="display_name" value="{{ old('display_name',$identity->display_name) }}"></label><label><span class="form-label">Status</span><select class="form-input" name="status">@foreach(['pending'=>'Pendente','approved'=>'Aprovado','rejected'=>'Rejeitado','blocked'=>'Bloqueado','inactive'=>'Inativo'] as $key=>$label)<option value="{{ $key }}" @selected($identity->status===$key)>{{ $label }}</option>@endforeach</select></label><label class="sm:col-span-2"><span class="form-label">Usuário ERP vinculado</span><select class="form-input" name="user_id"><option value="">Não vinculado</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected($identity->user_id===$user->id)>{{ $user->name }} · {{ $user->email }}</option>@endforeach</select></label></div></section>
<section class="form-card"><h2 class="section-title">Recursos do agente</h2><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['active'=>'Ativo','menu_enabled'=>'Menu','structured_commands_allowed'=>'Comandos estruturados','free_chat_allowed'=>'Conversa livre','voice_allowed'=>'Áudio','image_allowed'=>'Imagem','document_allowed'=>'Documentos','reports_allowed'=>'Relatórios'] as $field=>$label)<label class="flex gap-2"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field,$identity->$field))> {{ $label }}</label>@endforeach</div></section>
<section class="form-card"><h2 class="section-title">Cargo e unidades</h2><label class="mt-4 flex gap-2"><input type="checkbox" name="all_locations_access" value="1" @checked($identity->user?->all_locations_access)> Todas as unidades</label><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach($roles as $role)<label><input type="checkbox" name="role_ids[]" value="{{ $role->id }}" @checked($identity->user?->roles?->contains($role))> {{ $role->label }}</label>@endforeach</div><div class="mt-5 grid gap-3 sm:grid-cols-2">@foreach($locations as $location)<label><input type="checkbox" name="location_ids[]" value="{{ $location->id }}" @checked($identity->user?->locations?->contains($location))> {{ $location->name }}</label>@endforeach</div></section>
<section class="form-card"><h2 class="section-title">Overrides e permissões efetivas</h2><div class="mt-4 grid gap-4 md:grid-cols-2">@foreach($permissions as $permission) @php($pivot=$identity->user?->permissions?->firstWhere('id',$permission->id)?->pivot)<label><span class="form-label">{{ $permission->label }}</span><select class="form-input" name="permission_overrides[{{ $permission->id }}]"><option value="inherit" @selected(!$pivot)>Herdar</option><option value="allow" @selected($pivot?->allowed===true)>Permitir</option><option value="deny" @selected($pivot?->allowed===false)>Negar</option></select></label>@endforeach</div><div class="mt-5 flex flex-wrap gap-2">@forelse($effective as $name)<span class="status-badge status-active">{{ $name }}</span>@empty<span class="text-sm text-stone-500">Sem permissões efetivas.</span>@endforelse</div></section>
<button class="btn-primary">Salvar identidade e acessos</button></form>
@endsection
