@extends('layouts.app')
@section('title','WhatsApp do Agente')
@section('content')
<div class="page-header"><div><h1 class="page-title">WhatsApp do Agente</h1><p class="page-subtitle">Canal oficial Meta, disponibilidade e caixa de entrada persistente.</p></div><a class="btn-secondary" href="{{ route('agent.observability') }}">Observabilidade e custos</a></div>
@php($statusUi = match($connection->status){'operational'=>['🟢','OPERACIONAL','text-emerald-800 bg-emerald-50 border-emerald-200'],'degraded'=>['🟡','INSTABILIDADE','text-amber-800 bg-amber-50 border-amber-200'],default=>['🔴','INDISPONÍVEL','text-red-800 bg-red-50 border-red-200']})
<section class="form-card mb-6 border {{ $statusUi[2] }}"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-xl font-bold">{{ $statusUi[0] }} {{ $statusUi[1] }}</p><p class="mt-1 text-sm">Provider: Meta Cloud API · Última verificação: {{ $connection->last_checked_at?->format('d/m/Y H:i:s') ?? 'Nunca' }}</p>@if($connection->reason)<p class="mt-1 text-sm">Última falha: {{ $connection->reason }}</p>@endif</div><form method="POST" action="{{ route('agent.whatsapp.check') }}">@csrf<button class="btn-secondary">Verificar disponibilidade</button></form></div>
<div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><span class="form-label">Última recuperação</span>{{ $connection->last_connected_at?->format('d/m/Y H:i') ?? '—' }}</div><div><span class="form-label">Última indisponibilidade</span>{{ $connection->last_disconnected_at?->format('d/m/Y H:i') ?? '—' }}</div><div><span class="form-label">Última recebida</span>{{ $connection->last_received_at?->format('d/m/Y H:i') ?? '—' }}</div><div><span class="form-label">Última enviada</span>{{ $connection->last_sent_at?->format('d/m/Y H:i') ?? '—' }}</div></div></section>
<section><div class="mb-3 flex items-center justify-between"><h2 class="section-title">Mensagens pendentes / com erro</h2><span class="status-badge {{ $pendingCount ? 'status-inactive' : 'status-active' }}">{{ $pendingCount }}</span></div><div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Horário original</th><th>Remetente</th><th>Tipo</th><th>Status</th><th>Tentativas</th><th>Erro</th></tr></thead><tbody>@forelse($messages as $message)<tr><td>{{ $message->original_timestamp?->format('d/m/Y H:i:s') ?? $message->received_at->format('d/m/Y H:i:s') }}</td><td>{{ $message->external_user_id }}</td><td>{{ $message->message_type }}</td><td>{{ $message->status }}</td><td>{{ $message->attempts }}</td><td>{{ $message->error_code ?? '—' }}</td></tr>@empty<tr><td colspan="6" class="empty-state">Nenhuma mensagem recebida.</td></tr>@endforelse</tbody></table></div></div><div class="mt-4">{{ $messages->links() }}</div></section>
@endsection
