<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="name" class="form-label">Nome da boca/queimador</label><input id="name" name="name" class="form-input" required placeholder="Ex.: Boca frontal esquerda" value="{{ old('name', $burner?->name) }}"></div>
    <div><label for="type" class="form-label">Tipo</label><select id="type" name="type" class="form-input" required><option value="simple" @selected(old('type', $burner?->type) === 'simple')>Simples</option><option value="double" @selected(old('type', $burner?->type) === 'double')>Duplo</option><option value="custom" @selected(old('type', $burner?->type) === 'custom')>Personalizado</option></select></div>
    <div><label for="nominal_glp_consumption_kg_hour" class="form-label">Consumo nominal (kg GLP/h)</label><input id="nominal_glp_consumption_kg_hour" name="nominal_glp_consumption_kg_hour" type="number" min="0.000001" step="0.000001" class="form-input" required value="{{ old('nominal_glp_consumption_kg_hour', $burner?->nominal_glp_consumption_kg_hour) }}"><p class="mt-2 text-xs text-stone-500">Informe o valor real ou indicado pelo fabricante.</p></div>
    <div><label for="default_utilization_factor" class="form-label">Fator padrão de utilização</label><input id="default_utilization_factor" name="default_utilization_factor" type="number" min="0.001" max="1" step="0.001" class="form-input" required value="{{ old('default_utilization_factor', $burner?->default_utilization_factor ?? '1.000') }}"></div>
    <div><label for="power" class="form-label">Potência</label><input id="power" name="power" type="number" min="0.0001" step="0.0001" class="form-input" value="{{ old('power', $burner?->power) }}"></div>
    <div><label for="power_unit" class="form-label">Unidade da potência</label><input id="power_unit" name="power_unit" class="form-input" placeholder="Ex.: kW, kcal/h" value="{{ old('power_unit', $burner?->power_unit) }}"></div>
    <label class="sm:col-span-2 flex items-center gap-3 text-sm font-medium"><input type="checkbox" name="active" value="1" class="h-5 w-5 rounded border-stone-300 text-amber-600 focus:ring-amber-500" @checked(old('active', $burner?->active ?? true))> Queimador ativo</label>
</div>
