@extends('layouts.app')
@section('title', 'Produtos')
@section('content')
    <div class="page-header"><div><h1 class="page-title">Produtos</h1><p class="page-subtitle">Catálogo comercial em ordem operacional, com preço atual e situação da ficha técnica.</p></div><div class="flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('costs.index') }}">Custos e margens</a><a class="btn-primary" href="{{ route('products.create') }}">Novo produto</a></div></div>
    <div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Ordem</th><th>Nome</th><th>Categoria</th><th>Preço atual</th><th>Ficha</th><th>Status</th><th class="text-right">Ação</th></tr></thead><tbody>
        @forelse ($products as $product)<tr><td>{{ $product->sort_order ?? '—' }}</td><td><span class="font-semibold">{{ $product->name }}</span>@if($product->aliases->isNotEmpty())<span class="mt-1 block text-xs text-stone-500">Aliases: {{ $product->aliases->pluck('name')->implode(', ') }}</span>@endif</td><td>{{ $product->category?->name ?? '—' }}</td><td>{{ $product->currentPrice ? 'R$ '.\App\Support\DecimalFormatter::format($product->currentPrice->price, 2) : 'Pendente' }}</td><td>{{ $product->recipe ? 'Cadastrada' : 'Ficha técnica não cadastrada' }}</td><td><span class="status-badge {{ $product->active ? 'status-active' : 'status-inactive' }}">{{ $product->active ? 'Ativo' : 'Inativo' }}</span></td><td class="whitespace-nowrap text-right"><a class="text-link" href="{{ route('products.recipe.edit', $product) }}">Ficha técnica</a><a class="ml-3 text-link" href="{{ route('products.edit', $product) }}">Editar</a></td></tr>
        @empty <tr><td colspan="7" class="empty-state">Nenhum produto cadastrado.</td></tr> @endforelse
    </tbody></table></div></div><div class="mt-5">{{ $products->links() }}</div>
@endsection
