@extends('layouts.app')
@section('title','Ficha técnica')
@section('content')
<div class="page-header"><div><h1 class="page-title">Montagem — {{ $product->name }}</h1><p class="page-subtitle">Referências atuais de preparos e insumos; custos são recalculados em tempo real.</p></div></div>
@if(! $recipe)<div class="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><strong>Ficha técnica não cadastrada.</strong> Informe somente os componentes, quantidades e rendimentos reais. Nenhum custo será inventado.</div>@elseif(! $costs['is_complete'])<div class="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><strong>Sem custo calculado.</strong> Pendências: {{ implode('; ', $costs['missing_components']) }}. Subtotal conhecido por unidade: R$ {{ \App\Support\DecimalFormatter::format($costs['partial_unit_cost'],4) }}.</div>@endif
@if($costs)<div class="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="metric-card"><p class="metric-label">Custo atual/reposição</p><p class="metric-value">{{ $costs['unit_cost'] !== null ? 'R$ '.\App\Support\DecimalFormatter::format($costs['unit_cost'],4) : 'Sem custo calculado' }}</p></div><div class="metric-card"><p class="metric-label">Preço de venda</p><p class="metric-value">{{ $product->currentPrice ? 'R$ '.\App\Support\DecimalFormatter::format($product->currentPrice->price,2) : 'Pendente' }}</p></div><div class="metric-card"><p class="metric-label">Lucro bruto estimado</p><p class="metric-value">{{ $costs['gross_profit'] !== null ? 'R$ '.\App\Support\DecimalFormatter::format($costs['gross_profit'],2) : 'Pendente' }}</p></div><div class="metric-card"><p class="metric-label">Margem estimada</p><p class="metric-value">{{ $costs['gross_margin'] !== null ? \App\Support\DecimalFormatter::format($costs['gross_margin'],2).'%' : 'Pendente' }}</p></div></div>@endif
<form method="POST" action="{{ route('products.recipe.update',$product) }}" class="form-card">@csrf @method('PUT')
@if ($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label><span class="form-label">Peso final (g)</span><input class="form-input" name="final_weight_grams" value="{{ old('final_weight_grams',$recipe?->final_weight_grams) }}"></label><label><span class="form-label">Rendimento (un)</span><input class="form-input" name="yield_quantity" value="{{ old('yield_quantity',$recipe?->yield_quantity??1) }}" required></label><label><span class="form-label">Perda técnica (%)</span><input class="form-input" name="technical_loss_percentage" value="{{ old('technical_loss_percentage',$recipe?->technical_loss_percentage??0) }}" required></label><label><span class="form-label">Embalagem (R$)</span><input class="form-input" name="packaging_cost" value="{{ old('packaging_cost',$recipe?->packaging_cost??0) }}" required></label><label><span class="form-label">Preço de venda (R$)</span><input class="form-input" name="selling_price" value="{{ old('selling_price',$product->currentPrice?->price) }}"></label></div>
<h2 class="mt-6 text-lg font-bold">Preparos/recheios</h2><div class="grid gap-3 sm:grid-cols-3">@foreach($preparations as $index=>$preparation)@php($selected=$recipe?->preparations->firstWhere('preparation_id',$preparation->id))<label class="rounded-xl border p-3"><span class="font-semibold">{{ $preparation->name }}</span><input type="hidden" name="preparations[{{ $index }}][preparation_id]" value="{{ $preparation->id }}"><div class="mt-2 flex gap-2"><input class="form-input" name="preparations[{{ $index }}][quantity]" value="{{ $selected?->quantity }}" placeholder="Quantidade"><select class="form-input" name="preparations[{{ $index }}][unit]">@foreach(['g','kg','ml','l','un'] as $unit)<option @selected($selected?->unit===$unit)>{{ $unit }}</option>@endforeach</select></div></label>@endforeach</div>
<h2 class="mt-6 text-lg font-bold">Insumos adicionais</h2><div class="grid gap-3 sm:grid-cols-3">@foreach($ingredients as $index=>$ingredient)@php($selected=$recipe?->ingredients->firstWhere('ingredient_id',$ingredient->id))<label class="rounded-xl border p-3"><span class="font-semibold">{{ $ingredient->name }}</span><input type="hidden" name="ingredients[{{ $index }}][ingredient_id]" value="{{ $ingredient->id }}"><div class="mt-2 flex gap-2"><input class="form-input" name="ingredients[{{ $index }}][quantity]" value="{{ $selected?->quantity }}" placeholder="Quantidade"><select class="form-input" name="ingredients[{{ $index }}][unit]">@foreach(app(\App\Services\UnitConversionService::class)->allowedPurchaseUnits($ingredient->base_unit) as $unit)<option @selected($selected?->unit===$unit)>{{ $unit }}</option>@endforeach</select></div></label>@endforeach</div>
<label class="mt-5 block"><span class="form-label">Observações</span><textarea class="form-input" name="notes">{{ old('notes',$recipe?->notes) }}</textarea></label><button class="btn-primary mt-5">Salvar ficha técnica</button></form>
@endsection
