@extends('layouts.app')
@section('title','Ficha técnica')
@section('content')
<div class="page-header"><div><h1 class="page-title">Montagem — {{ $product->name }}</h1><p class="page-subtitle">Referências atuais de preparos e insumos; custos são recalculados em tempo real.</p></div></div>
@if($costs)<div class="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="metric-card"><p class="metric-label">Custo direto unitário</p><p class="metric-value">R$ {{ \App\Support\DecimalFormatter::format($costs['unit_cost'],4) }}</p></div><div class="metric-card"><p class="metric-label">Preço de venda</p><p class="metric-value">R$ {{ \App\Support\DecimalFormatter::format($recipe->selling_price ?? '0',2) }}</p></div><div class="metric-card"><p class="metric-label">Lucro bruto</p><p class="metric-value">R$ {{ \App\Support\DecimalFormatter::format($costs['gross_profit'] ?? '0',2) }}</p></div><div class="metric-card"><p class="metric-label">Margem bruta</p><p class="metric-value">{{ \App\Support\DecimalFormatter::format($costs['gross_margin'] ?? '0',2) }}%</p></div></div>@endif
<form method="POST" action="{{ route('products.recipe.update',$product) }}" class="form-card">@csrf @method('PUT')
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label><span class="form-label">Peso final (g)</span><input class="form-input" name="final_weight_grams" value="{{ old('final_weight_grams',$recipe?->final_weight_grams) }}"></label><label><span class="form-label">Rendimento (un)</span><input class="form-input" name="yield_quantity" value="{{ old('yield_quantity',$recipe?->yield_quantity??1) }}" required></label><label><span class="form-label">Perda técnica (%)</span><input class="form-input" name="technical_loss_percentage" value="{{ old('technical_loss_percentage',$recipe?->technical_loss_percentage??0) }}" required></label><label><span class="form-label">Embalagem (R$)</span><input class="form-input" name="packaging_cost" value="{{ old('packaging_cost',$recipe?->packaging_cost??0) }}" required></label><label><span class="form-label">Preço de venda (R$)</span><input class="form-input" name="selling_price" value="{{ old('selling_price',$recipe?->selling_price) }}"></label></div>
<h2 class="mt-6 text-lg font-bold">Preparos/recheios</h2><div class="grid gap-3 sm:grid-cols-3">@foreach($preparations as $index=>$preparation)@php($selected=$recipe?->preparations->firstWhere('preparation_id',$preparation->id))<label class="rounded-xl border p-3"><span class="font-semibold">{{ $preparation->name }}</span><input type="hidden" name="preparations[{{ $index }}][preparation_id]" value="{{ $preparation->id }}"><div class="mt-2 flex gap-2"><input class="form-input" name="preparations[{{ $index }}][quantity]" value="{{ $selected?->quantity }}" placeholder="Quantidade"><select class="form-input" name="preparations[{{ $index }}][unit]">@foreach(['g','kg','ml','l','un'] as $unit)<option @selected($selected?->unit===$unit)>{{ $unit }}</option>@endforeach</select></div></label>@endforeach</div>
<h2 class="mt-6 text-lg font-bold">Insumos adicionais</h2><div class="grid gap-3 sm:grid-cols-3">@foreach($ingredients as $index=>$ingredient)@php($selected=$recipe?->ingredients->firstWhere('ingredient_id',$ingredient->id))<label class="rounded-xl border p-3"><span class="font-semibold">{{ $ingredient->name }}</span><input type="hidden" name="ingredients[{{ $index }}][ingredient_id]" value="{{ $ingredient->id }}"><div class="mt-2 flex gap-2"><input class="form-input" name="ingredients[{{ $index }}][quantity]" value="{{ $selected?->quantity }}" placeholder="Quantidade"><select class="form-input" name="ingredients[{{ $index }}][unit]">@foreach(app(\App\Services\UnitConversionService::class)->allowedPurchaseUnits($ingredient->base_unit) as $unit)<option @selected($selected?->unit===$unit)>{{ $unit }}</option>@endforeach</select></div></label>@endforeach</div>
<label class="mt-5 block"><span class="form-label">Observações</span><textarea class="form-input" name="notes">{{ old('notes',$recipe?->notes) }}</textarea></label><button class="btn-primary mt-5">Salvar ficha técnica</button></form>
@endsection
