@extends('layouts.app')
@inject('authorization', 'App\Services\AuthorizationService')
@section('title', 'Vendas')
@section('content')
<div class="page-header"><div><h1 class="page-title">Vendas</h1><p class="page-subtitle">Saídas comerciais e faturamento por período.</p></div>@if($authorization->allows(auth()->user(), 'sales.create'))<a class="btn-primary" href="{{ route('sales.create') }}">Registrar venda</a>@endif</div>
<form class="form-card mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5" method="GET"><label><span class="form-label">Unidade</span><select class="form-input" name="location_id">@foreach($locations as $item)<option value="{{ $item->id }}" @selected($location?->id===$item->id)>{{ $item->name }}</option>@endforeach</select></label><label><span class="form-label">Início</span><input class="form-input" type="date" name="start_date" value="{{ $startDate }}"></label><label><span class="form-label">Fim</span><input class="form-input" type="date" name="end_date" value="{{ $endDate }}"></label><label><span class="form-label">Pagamento</span><select class="form-input" name="payment_method"><option value="">Todos</option>@foreach($paymentMethods as $method)<option value="{{ $method->value }}" @selected($paymentMethod===$method->value)>{{ $method->label() }}</option>@endforeach</select></label><button class="btn-secondary self-end">Filtrar</button></form>
<div class="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><div class="form-card"><p class="text-sm text-stone-500">Faturamento bruto</p><p class="mt-1 text-2xl font-bold">R$ {{ \App\Support\DecimalFormatter::format((string)($summary['revenue'] ?? 0), 2) }}</p></div><div class="form-card"><p class="text-sm text-stone-500">Taxas</p><p class="mt-1 text-2xl font-bold">R$ {{ \App\Support\DecimalFormatter::format((string)($summary['fees'] ?? 0), 2) }}</p></div><div class="form-card"><p class="text-sm text-stone-500">Receita líquida</p><p class="mt-1 text-2xl font-bold">R$ {{ \App\Support\DecimalFormatter::format((string)($summary['net'] ?? 0), 2) }}</p></div><div class="form-card"><p class="text-sm text-stone-500">CPV conhecido</p><p class="mt-1 text-2xl font-bold">R$ {{ \App\Support\DecimalFormatter::format((string)($summary['cost_of_goods'] ?? 0), 2) }}</p></div><div class="form-card"><p class="text-sm text-stone-500">Lucro bruto</p><p class="mt-1 text-2xl font-bold">{{ ($summary['gross_profit'] ?? null) === null ? '—' : 'R$ '.\App\Support\DecimalFormatter::format($summary['gross_profit'],2) }}</p></div><div class="form-card"><p class="text-sm text-stone-500">Margem</p><p class="mt-1 text-2xl font-bold">{{ ($summary['gross_margin_percentage'] ?? null) === null ? '—' : \App\Support\DecimalFormatter::format($summary['gross_margin_percentage'],2).'%' }}</p></div></div>
@if(($summary['missing_cost_count'] ?? 0)>0)<div class="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{{ $summary['missing_cost_count'] }} venda(s) sem ficha/custo completo não foram tratadas como custo zero.</div>@endif
<div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Data</th><th>Unidade</th><th>Produto</th><th>Pagamento</th><th>Bruto</th><th>Taxa</th><th>Líquido</th><th>CPV</th><th>Lucro bruto</th></tr></thead><tbody>@forelse($sales as $sale)<tr><td>{{ $sale->operation_date->format('d/m/Y') }}</td><td>{{ $sale->location->name }}</td><td class="font-semibold">{{ $sale->product->name }}</td><td><strong>{{ \App\Enums\ProductSalePaymentMethod::tryFrom($sale->payment_method)?->label() ?? $sale->payment_method }}</strong>@if($sale->acquirer)<span class="block text-xs text-stone-500">{{ $sale->acquirer->name }}{{ $sale->cardBrand ? ' · '.$sale->cardBrand->name : '' }}</span>@endif</td><td>R$ {{ \App\Support\DecimalFormatter::format($sale->gross_amount ?? $sale->total_amount, 2) }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($sale->fee_amount_snapshot ?? '0', 2) }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($sale->net_amount ?? $sale->total_amount, 2) }}</td><td>{{ $sale->total_cost_snapshot === null ? 'Pendente' : 'R$ '.\App\Support\DecimalFormatter::format($sale->total_cost_snapshot,2) }}</td><td>{{ $sale->gross_profit_snapshot === null ? 'Pendente' : 'R$ '.\App\Support\DecimalFormatter::format($sale->gross_profit_snapshot,2) }}</td></tr>@empty<tr><td colspan="9" class="empty-state">Nenhuma venda registrada.</td></tr>@endforelse</tbody></table></div></div><div class="mt-5">{{ $sales->links() }}</div>
@endsection
