@extends('layouts.app')
@inject('authorization', 'App\Services\AuthorizationService')
@section('title', 'Vendas')
@section('content')
<div class="page-header"><div><h1 class="page-title">Vendas</h1><p class="page-subtitle">Saídas comerciais e faturamento por período.</p></div>@if($authorization->allows(auth()->user(), 'sales.create'))<a class="btn-primary" href="{{ route('sales.create') }}">Registrar venda</a>@endif</div>
<form class="form-card mb-6 grid gap-4 sm:grid-cols-4" method="GET"><label><span class="form-label">Unidade</span><select class="form-input" name="location_id">@foreach($locations as $item)<option value="{{ $item->id }}" @selected($location?->id===$item->id)>{{ $item->name }}</option>@endforeach</select></label><label><span class="form-label">Início</span><input class="form-input" type="date" name="start_date" value="{{ $startDate }}"></label><label><span class="form-label">Fim</span><input class="form-input" type="date" name="end_date" value="{{ $endDate }}"></label><button class="btn-secondary self-end">Filtrar</button></form>
<div class="mb-6 grid gap-4 sm:grid-cols-3"><div class="form-card"><p class="text-sm text-stone-500">Faturamento bruto</p><p class="mt-1 text-2xl font-bold">R$ {{ \App\Support\DecimalFormatter::format((string)($summary['revenue'] ?? 0), 2) }}</p></div><div class="form-card"><p class="text-sm text-stone-500">Taxas</p><p class="mt-1 text-2xl font-bold">R$ {{ \App\Support\DecimalFormatter::format((string)($summary['fees'] ?? 0), 2) }}</p></div><div class="form-card"><p class="text-sm text-stone-500">Receita líquida</p><p class="mt-1 text-2xl font-bold">R$ {{ \App\Support\DecimalFormatter::format((string)($summary['net'] ?? 0), 2) }}</p></div></div>
<div class="table-card"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Data</th><th>Unidade</th><th>Produto</th><th>Pagamento</th><th>Bruto</th><th>Taxa</th><th>Líquido</th></tr></thead><tbody>@forelse($sales as $sale)<tr><td>{{ $sale->operation_date->format('d/m/Y') }}</td><td>{{ $sale->location->name }}</td><td class="font-semibold">{{ $sale->product->name }}</td><td>{{ $sale->acquirer?->name ?? 'Sem adquirente' }} {{ $sale->cardBrand ? '· '.$sale->cardBrand->name : '' }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($sale->gross_amount ?? $sale->total_amount, 2) }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($sale->fee_amount_snapshot ?? '0', 2) }}</td><td>R$ {{ \App\Support\DecimalFormatter::format($sale->net_amount ?? $sale->total_amount, 2) }}</td></tr>@empty<tr><td colspan="7" class="empty-state">Nenhuma venda registrada.</td></tr>@endforelse</tbody></table></div></div><div class="mt-5">{{ $sales->links() }}</div>
@endsection
