@extends('layouts.app')
@section('title', 'Revisão da compra')
@section('content')
@php($editable = !in_array($import->status, ['confirmed','cancelled','duplicate']))
<div class="page-header"><div><div class="flex flex-wrap items-center gap-3"><h1 class="page-title">Revisão #{{ $import->id }}</h1><span class="status-badge {{ $import->status === 'confirmed' ? 'status-active' : '' }}">{{ str_replace('_',' ',$import->status) }}</span></div><p class="page-subtitle">{{ $import->location->name }} · criado em {{ $import->created_at->format('d/m/Y H:i') }}</p></div><a class="btn-secondary" href="{{ route('purchase-imports.index') }}">Voltar</a></div>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
@if($import->warnings)<div class="mb-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>Pontos a conferir:</strong><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($import->warnings as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif
<section class="form-card mb-6"><h2 class="text-lg font-bold">Arquivos originais protegidos</h2><div class="mt-3 flex flex-wrap gap-2">@foreach($import->attachments as $attachment)<a class="btn-secondary" href="{{ route('attachments.download', $attachment) }}">Página {{ $attachment->pivot->page_order }} · {{ $attachment->original_name }}</a>@endforeach</div></section>

@if($import->confirmedDocument)<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900">Documento oficial criado: <a class="font-bold underline" href="{{ route('purchases.show', $import->confirmedDocument) }}">compra #{{ $import->confirmedDocument->id }}</a>.</div>@endif

@if($import->items->isNotEmpty())
<form method="POST" action="{{ route('purchase-imports.update', $import) }}" class="space-y-6">@csrf @method('PUT')
    <section class="form-card"><div class="mb-4 flex items-center justify-between"><h2 class="text-lg font-bold">Documento e fornecedor</h2><span class="text-xs font-semibold uppercase text-stone-500">Extraído → confirmado</span></div>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <label><span class="form-label">Tipo</span><select class="form-input" name="document_type" @disabled(!$editable)>@foreach(['purchase_invoice'=>'Nota fiscal','purchase_receipt'=>'Cupom/recibo','purchase_order'=>'Pedido de compra','quotation'=>'Cotação'] as $value=>$label)<option value="{{ $value }}" @selected(old('document_type',$import->document_type)===$value)>{{ $label }}</option>@endforeach</select></label>
            <label class="sm:col-span-2"><span class="form-label">Fornecedor <small class="font-normal text-stone-500">extraído: {{ $import->supplier_name_extracted ?: 'não identificado' }}</small></span><select class="form-input" name="supplier_id" required @disabled(!$editable)><option value="">Selecione</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id',$import->supplier_id)==$supplier->id)>{{ $supplier->name }}</option>@endforeach</select>@if($editable)<a class="mt-2 inline-block text-link" href="{{ route('suppliers.create') }}" target="_blank" rel="noopener">Fornecedor não cadastrado? Abrir cadastro</a>@endif</label>
            <label><span class="form-label">Número</span><input class="form-input" name="document_number" value="{{ old('document_number',$import->document_number) }}" @disabled(!$editable)></label>
            <label><span class="form-label">Série</span><input class="form-input" name="series" value="{{ old('series',$import->series) }}" @disabled(!$editable)></label>
            <label><span class="form-label">Data de emissão</span><input class="form-input" type="date" name="issue_date" value="{{ old('issue_date',$import->issue_date?->toDateString()) }}" required @disabled(!$editable)></label>
            <label><span class="form-label">Chave de acesso</span><input class="form-input" name="access_key" value="{{ old('access_key',$import->access_key) }}" @disabled(!$editable)></label>
            <label><span class="form-label">Subtotal</span><input class="form-input" name="gross_amount" value="{{ old('gross_amount',$import->gross_amount) }}" @disabled(!$editable)></label>
            <label><span class="form-label">Desconto</span><input class="form-input" name="discount_amount" value="{{ old('discount_amount',$import->discount_amount ?? '0.00') }}" required @disabled(!$editable)></label>
            <label><span class="form-label">Frete</span><input class="form-input" name="freight_amount" value="{{ old('freight_amount',$import->freight_amount ?? '0.00') }}" required @disabled(!$editable)></label>
            <label><span class="form-label">Outros acréscimos</span><input class="form-input" name="other_charges_amount" value="{{ old('other_charges_amount',$import->other_charges_amount ?? '0.00') }}" required @disabled(!$editable)></label>
            <label><span class="form-label">Total do documento</span><input class="form-input font-bold" name="total_amount" value="{{ old('total_amount',$import->total_amount) }}" required @disabled(!$editable)></label>
        </div>
    </section>
    <section><div class="mb-4"><h2 class="text-xl font-bold">Itens extraídos e vínculos com o ERP</h2><p class="text-sm text-stone-500">O texto do fornecedor permanece específico deste fornecedor; ele não vira um apelido global.</p></div>
        <div class="space-y-4">@foreach($import->items as $item)<article class="form-card">
            <div class="mb-4 flex flex-wrap items-start justify-between gap-2"><div><p class="text-xs font-bold uppercase tracking-wide text-stone-500">Linha {{ $item->line_number }} · texto extraído</p><h3 class="text-lg font-bold">{{ $item->description }}</h3>@if($item->external_code)<p class="text-sm text-stone-500">Código externo: {{ $item->external_code }}</p>@endif</div><span class="status-badge">{{ str_replace('_',' ',$item->mapping_status) }}</span></div>
            <input type="hidden" name="items[{{ $item->id }}][description]" value="{{ $item->description }}"><input type="hidden" name="items[{{ $item->id }}][external_code]" value="{{ $item->external_code }}">
            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">
                <label class="lg:col-span-2"><span class="form-label">Insumo confirmado</span><select class="form-input" name="items[{{ $item->id }}][ingredient_id]" required @disabled(!$editable)><option value="">Selecione</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}" @selected(old("items.{$item->id}.ingredient_id",$item->ingredient_id)==$ingredient->id)>{{ $ingredient->name }}{{ $ingredient->brand ? ' · '.$ingredient->brand : '' }}</option>@endforeach</select>@if($editable)<a class="mt-2 inline-block text-link" href="{{ route('ingredients.create') }}" target="_blank" rel="noopener">Insumo não cadastrado? Abrir cadastro</a>@endif</label>
                <label><span class="form-label">Quantidade</span><input class="form-input" name="items[{{ $item->id }}][quantity]" value="{{ old("items.{$item->id}.quantity",$item->quantity) }}" required @disabled(!$editable)></label>
                <label><span class="form-label">Unidade</span><select class="form-input" name="items[{{ $item->id }}][unit]" required @disabled(!$editable)>@foreach(['kg','g','l','ml','un'] as $unit)<option @selected(old("items.{$item->id}.unit",$item->unit)===$unit)>{{ $unit }}</option>@endforeach</select></label>
                <label><span class="form-label">Nº embalagens</span><input class="form-input" name="items[{{ $item->id }}][package_quantity]" value="{{ old("items.{$item->id}.package_quantity",$item->package_quantity) }}" @disabled(!$editable)></label>
                <label><span class="form-label">Tamanho embalagem</span><input class="form-input" name="items[{{ $item->id }}][package_size]" value="{{ old("items.{$item->id}.package_size",$item->package_size) }}" @disabled(!$editable)></label>
                <label><span class="form-label">Un. embalagem</span><select class="form-input" name="items[{{ $item->id }}][package_unit]" @disabled(!$editable)><option value="">—</option>@foreach(['kg','g','l','ml','un'] as $unit)<option @selected(old("items.{$item->id}.package_unit",$item->package_unit)===$unit)>{{ $unit }}</option>@endforeach</select></label>
                <label><span class="form-label">Bruto</span><input class="form-input" name="items[{{ $item->id }}][gross_amount]" value="{{ old("items.{$item->id}.gross_amount",$item->gross_amount ?? $item->net_amount) }}" required @disabled(!$editable)></label>
                <label><span class="form-label">Líquido</span><input class="form-input font-bold" name="items[{{ $item->id }}][net_amount]" value="{{ old("items.{$item->id}.net_amount",$item->net_amount) }}" required @disabled(!$editable)></label>
                @foreach(['discount_amount'=>'Desconto','freight_amount'=>'Frete rateado','other_charges_amount'=>'Acréscimos'] as $field=>$label)<label><span class="form-label">{{ $label }}</span><input class="form-input" name="items[{{ $item->id }}][{{ $field }}]" value="{{ old("items.{$item->id}.{$field}",$item->{$field} ?? '0.00') }}" required @disabled(!$editable)></label>@endforeach
            </div>
            @if($item->ingredient)<div class="mt-4 grid gap-3 rounded-xl bg-stone-50 p-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><strong>Custo extraído normalizado</strong><br>{{ $item->normalized_unit_cost ? 'R$ '.\App\Support\DecimalFormatter::format($item->normalized_unit_cost,4).' / '.$item->normalized_unit : 'Pendente' }}</div><div><strong>Custo atual no ERP</strong><br>{{ $item->ingredient->currentPrice ? 'R$ '.\App\Support\DecimalFormatter::format($item->ingredient->currentPrice->base_unit_cost,4).' / '.$item->ingredient->base_unit : 'Sem preço' }}</div><div><strong>Variação proposta</strong><br>@if(data_get($priceComparisons,$item->id.'.status')==='first_price')Primeiro preço registrado deste fornecedor/insumo.@elseif(data_get($priceComparisons,$item->id.'.difference')!==null)R$ {{ \App\Support\DecimalFormatter::format(data_get($priceComparisons,$item->id.'.difference'),4) }} · {{ data_get($priceComparisons,$item->id.'.variation_percentage')===null ? '—' : \App\Support\DecimalFormatter::format(data_get($priceComparisons,$item->id.'.variation_percentage'),2).'%' }}@else Pendente @endif</div><div><strong>Compras nos últimos 30 dias</strong><br>{{ data_get($priceSummaries,$item->id.'.count',0) }}</div></div>@endif
        </article>@endforeach</div>
    </section>
    @if($editable)<section class="form-card"><h2 class="text-lg font-bold">Efeito operacional</h2><label class="mt-3 flex items-start gap-3"><input type="checkbox" name="received" value="1" @checked(old('received',data_get($import->interpretation,'received',false)))><span><strong>A mercadoria já foi recebida fisicamente</strong><small class="block text-stone-500">Somente esta confirmação cria a entrada no estoque de insumos.</small></span></label><label class="mt-4 block max-w-xs"><span class="form-label">Data real do recebimento</span><input class="form-input" type="date" name="received_date" value="{{ old('received_date',data_get($import->interpretation,'received_date',$import->issue_date?->toDateString())) }}"></label><p class="mt-3 text-sm text-stone-500">Conta a pagar não será criada automaticamente; ela continuará como uma ação separada no documento oficial.</p><button class="btn-primary mt-5">Salvar revisão</button></section>@endif
</form>
@endif

@if($editable)<div class="mt-6 flex flex-wrap gap-3">@if($import->status === 'ready_for_confirmation')<form method="POST" action="{{ route('purchase-imports.confirm',$import) }}">@csrf<button class="btn-primary">Confirmar e criar compra oficial</button></form>@endif<form method="POST" action="{{ route('purchase-imports.cancel',$import) }}">@csrf<button class="btn-secondary">Cancelar sem gravar</button></form></div>@endif
@endsection
